export enum BooksName {
    SAHIH_BUKHARI = 'SAHIH_BUKHARI',
    SAHIH_MUSLIM = 'SAHIH_MUSLIM',
    SUNAN_ABI_DAUD = 'SUNAN_ABI_DAUD',
    SUNAN_TIRMIZHI = 'SUNAN_TIRMIZHI',
    SUNAN_NASAI = 'SUNAN_NASAI',
    SUNAN_IBNU_MAJAH = 'SUNAN_IBNU_MAJAH',
    RIYAD_AS_SOLIHIN = 'RIYAD_AS_SOLIHIN',
}